/** ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**
**     @file      lin_cfg.c
**
**     @date      14:31:49, 2022-2-10
**
**     @brief     Hardware configuration file
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016 - 2017 NXP
**     All Rights Reserved.
**
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/

/*!
 * @file lin_cfg.c
 *
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, Could be made static.
 * Function ld_read_by_id_callout is API and shall not be made static.
 * This API is declared in lin_cfg.c so that users can configure the response
 * for  Read by ID request.
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.9, An object should be defined at block
 * scope if its identifier only appears in a single function.
 * An object with static storage duration declared at block scope cannot be
 * accessed directly from outside the block. g_lin_hardware_ifc, g_lin_tl_descriptor_array,
 * timerGetTimeIntervalCallback are dependent on user configurations,
 * so they shall be declared in lin_cfg.c.
 */

#include "lin.h"


#if (SUPPORT_TRANSPORT_LAYER == 1U)
static lin_tl_pdu_data_t      LI0_tl_tx_queue_data[2];
static lin_tl_pdu_data_t      LI0_tl_rx_queue_data[2];
#endif /* end (SUPPORT_TRANSPORT_LAYER == 1U) */

const l_ifc_handle g_lin_hardware_ifc[HARDWARE_INSTANCE_COUNT] = {INVALID_IFC, LI0, INVALID_IFC};
const l_u32 g_lin_virtual_ifc[LIN_NUM_OF_IFCS] = {1};
volatile l_u8 g_buffer_backup_data[8] = {0, 0, 0, 0, 0, 0, 0, 0};

/* definition and initialization of signal array */
volatile l_u8    g_lin_frame_data_buffer[LIN_FRAME_BUF_SIZE] =
{
  0xfe /* 0 : 11111110 */ /* start of frame LI0_BDC_1_Cmd */

  ,0x08 /* 1 : 00001000 */

  ,0xff /* 2 : 11111111 */

  ,0xff /* 3 : 11111111 */

  ,0xff /* 4 : 11111111 */

  ,0xff /* 5 : 11111111 */

  ,0xff /* 6 : 11111111 */

  ,0xff /* 7 : 11111111 */

  ,0xc2 /* 8 : 11000010 */ /* start of frame LI0_BDC_1_Rsp */

  ,0x0f /* 9 : 00001111 */

  ,0x00 /* 10 : 00000000 */

  ,0xff /* 11 : 11111111 */

  ,0xff /* 12 : 11111111 */

  ,0xff /* 13 : 11111111 */

  ,0xff /* 14 : 11111111 */

  ,0xff /* 15 : 11111111 */

  ,0xfe /* 16 : 11111110 */ /* start of frame LI0_BDC_2_Cmd */

  ,0x08 /* 17 : 00001000 */

  ,0xff /* 18 : 11111111 */

  ,0xff /* 19 : 11111111 */

  ,0xff /* 20 : 11111111 */

  ,0xff /* 21 : 11111111 */

  ,0xff /* 22 : 11111111 */

  ,0xff /* 23 : 11111111 */

  ,0xc2 /* 24 : 11000010 */ /* start of frame LI0_BDC_2_Rsp */

  ,0x0f /* 25 : 00001111 */

  ,0x00 /* 26 : 00000000 */

  ,0xff /* 27 : 11111111 */

  ,0xff /* 28 : 11111111 */

  ,0xff /* 29 : 11111111 */

  ,0xff /* 30 : 11111111 */

  ,0xff /* 31 : 11111111 */

  ,0xfc /* 32 : 11111100 */ /* start of frame LI0_CCV4_Cmd */

  ,0xff /* 33 : 11111111 */

  ,0xff /* 34 : 11111111 */

  ,0xff /* 35 : 11111111 */

  ,0xff /* 36 : 11111111 */

  ,0xff /* 37 : 11111111 */

  ,0xff /* 38 : 11111111 */

  ,0xff /* 39 : 11111111 */

  ,0x02 /* 40 : 00000010 */ /* start of frame LI0_CCV4_Rsq */

  ,0x0f /* 41 : 00001111 */

  ,0xff /* 42 : 11111111 */

  ,0xff /* 43 : 11111111 */

  ,0xff /* 44 : 11111111 */

  ,0xff /* 45 : 11111111 */

  ,0xff /* 46 : 11111111 */

  ,0xff /* 47 : 11111111 */

  ,0x00 /* 48 : 00000000 */ /* start of frame LI0_ATC_4 */

  ,0x00 /* 49 : 00000000 */

  ,0xfe /* 50 : 11111110 */

  ,0xf8 /* 51 : 11111000 */

  ,0xff /* 52 : 11111111 */

  ,0xff /* 53 : 11111111 */

  ,0xff /* 54 : 11111111 */

  ,0xff /* 55 : 11111111 */

  ,0x00 /* 56 : 00000000 */ /* start of frame LI0_EXV_2 */

  ,0xf0 /* 57 : 11110000 */

  ,0x00 /* 58 : 00000000 */

  ,0x00 /* 59 : 00000000 */

  ,0xff /* 60 : 11111111 */

  ,0xff /* 61 : 11111111 */

  ,0xff /* 62 : 11111111 */

  ,0xff /* 63 : 11111111 */

  ,0x00 /* 64 : 00000000 */ /* start of frame LI0_VCU_EXV */

  ,0x00 /* 65 : 00000000 */

  ,0xfe /* 66 : 11111110 */

  ,0xf8 /* 67 : 11111000 */

  ,0xff /* 68 : 11111111 */

  ,0xff /* 69 : 11111111 */

  ,0xff /* 70 : 11111111 */

  ,0xff /* 71 : 11111111 */

  ,0x00 /* 72 : 00000000 */ /* start of frame LI0_EXV_VCU */

  ,0xf0 /* 73 : 11110000 */

  ,0x00 /* 74 : 00000000 */

  ,0x00 /* 75 : 00000000 */

  ,0xff /* 76 : 11111111 */

  ,0xff /* 77 : 11111111 */

  ,0xff /* 78 : 11111111 */

  ,0xff /* 79 : 11111111 */

  ,0x00 /* 80 : 00000000 */ /* start of frame LI0_VCU_EXV2 */

  ,0x00 /* 81 : 00000000 */

  ,0xfe /* 82 : 11111110 */

  ,0xf8 /* 83 : 11111000 */

  ,0xff /* 84 : 11111111 */

  ,0xff /* 85 : 11111111 */

  ,0xff /* 86 : 11111111 */

  ,0xff /* 87 : 11111111 */

  ,0x00 /* 88 : 00000000 */ /* start of frame LI0_EXV2_VCU */

  ,0xf0 /* 89 : 11110000 */

  ,0x00 /* 90 : 00000000 */

  ,0x00 /* 91 : 00000000 */

  ,0xff /* 92 : 11111111 */

  ,0xff /* 93 : 11111111 */

  ,0xff /* 94 : 11111111 */

  ,0xff /* 95 : 11111111 */

  ,0x00 /* 96 : 00000000 */ /* start of frame LI0_ECM_AGM_A_DEMAND */

  ,0xfa /* 97 : 11111010 */

  ,0x00 /* 98 : 00000000 */

  ,0xff /* 99 : 11111111 */

  ,0x7f /* 100 : 01111111 */ /* start of frame LI0_AGM_A_ECM_STATUS */

  ,0x0a /* 101 : 00001010 */

  ,0xfe /* 102 : 11111110 */

  ,0xff /* 103 : 11111111 */

  ,0x00 /* 104 : 00000000 */ /* start of frame LI0_ECM_AGM_B_DEMAND */

  ,0xfa /* 105 : 11111010 */

  ,0x00 /* 106 : 00000000 */

  ,0xff /* 107 : 11111111 */

  ,0x7f /* 108 : 01111111 */ /* start of frame LI0_AGM_B_ECM_STATUS */

  ,0x0a /* 109 : 00001010 */

  ,0xfe /* 110 : 11111110 */

  ,0xff /* 111 : 11111111 */
};

/* definition and initialization of signal array */
volatile l_u8    g_lin_flag_handle_tbl[LIN_FLAG_BUF_SIZE] =
{
  0xFF /* 0: start of flag frame LI0_BDC_1_Cmd */

  ,0xFF /* 1: start of flag frame LI0_BDC_1_Rsp */

  ,0xFF /* 2: start of flag frame LI0_BDC_2_Cmd */

  ,0xFF /* 3: start of flag frame LI0_BDC_2_Rsp */

  ,0xFF /* 4: start of flag frame LI0_CCV4_Cmd */

  ,0xFF /* 5: start of flag frame LI0_CCV4_Rsq */

  ,0xFF /* 6: start of flag frame LI0_ATC_4 */

  ,0xFF /* 7: start of flag frame LI0_EXV_2 */

  ,0xFF /* 8: start of flag frame LI0_VCU_EXV */

  ,0xFF /* 9: start of flag frame LI0_EXV_VCU */

  ,0xFF /* 10: start of flag frame LI0_VCU_EXV2 */

  ,0xFF /* 11: start of flag frame LI0_EXV2_VCU */

  ,0xFF /* 12: start of flag frame LI0_ECM_AGM_A_DEMAND */

  ,0xFF /* 13: start of flag frame LI0_AGM_A_ECM_STATUS */

  ,0xFF /* 14: */

  ,0xFF /* 15: start of flag frame LI0_ECM_AGM_B_DEMAND */

  ,0xFF /* 16: start of flag frame LI0_AGM_B_ECM_STATUS */

  ,0xFF /* 17: */
};

/* definition and initialization for flag of frame */
volatile l_bool g_lin_frame_flag_handle_tbl[LIN_NUM_OF_FRMS] = {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false};

/*************************** Frame flag for updating signal in frame ****************/
volatile l_u8 g_lin_frame_updating_flag_tbl[LIN_NUM_OF_FRMS] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};



/*****************************sporadic frame*****************************/
/*all sporadic frames for master node*/
/**********************************  Frame table **********************************/
static const lin_frame_t lin_frame_tbl[LIN_NUM_OF_FRMS] ={

    { LIN_FRM_UNCD, 8, LIN_RES_PUB, 0, 0, 1   , (lin_associate_frame_t*)0 }

   ,{ LIN_FRM_UNCD, 8, LIN_RES_SUB, 8, 1, 1 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_UNCD, 8, LIN_RES_PUB, 16, 2, 1 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_UNCD, 8, LIN_RES_SUB, 24, 3, 1 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_UNCD, 8, LIN_RES_PUB, 32, 4, 1 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_UNCD, 8, LIN_RES_SUB, 40, 5, 1 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_UNCD, 8, LIN_RES_PUB, 48, 6, 1 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_UNCD, 8, LIN_RES_SUB, 56, 7, 1 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_UNCD, 8, LIN_RES_PUB, 64, 8, 1 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_UNCD, 8, LIN_RES_SUB, 72, 9, 1 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_UNCD, 8, LIN_RES_PUB, 80, 10, 1 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_UNCD, 8, LIN_RES_SUB, 88, 11, 1 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_UNCD, 4, LIN_RES_PUB, 96, 12, 1 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_UNCD, 4, LIN_RES_SUB, 100, 13, 2 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_UNCD, 4, LIN_RES_PUB, 104, 15, 1 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_UNCD, 4, LIN_RES_SUB, 108, 16, 2 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_DIAG, 8, LIN_RES_PUB, 0, 0, 0 , (lin_associate_frame_t*)0 }
  
   ,{ LIN_FRM_DIAG, 8, LIN_RES_SUB, 0, 0, 0 , (lin_associate_frame_t*)0 }
  
};

static l_u8 LI0_lin_configuration_RAM[LI0_LIN_SIZE_OF_CFG]= {0x00, 0x2A, 0x2B, 0x29, 0x28, 0x19, 0x09, 0x12, 0x22, 0x11, 0x21, 0x1E, 0x1F, 0x1C, 0x1B, 0x14, 0x13, 0x3C, 0x3D ,0xFF};

static const l_u16  LI0_lin_configuration_ROM[LI0_LIN_SIZE_OF_CFG]= {0x0000, 0x2A, 0x2B, 0x29, 0x28, 0x19, 0x09, 0x12, 0x22, 0x11, 0x21, 0x1E, 0x1F, 0x1C, 0x1B, 0x14, 0x13, 0x3C, 0x3D ,0xFFFF};


/********************** Go to sleep Initialization *************************/
/* Delay of this schedule table is: (1.4*(34+10*(8+1))*1000/LIN_speed+jitter) ms */
/* then rounded up to a value is multiple of time base */
static const lin_schedule_data_t LI0_lin_gotosleep_data[1] = {
   {LI0_MasterReq, 3, {0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF}}
};


/******************** Schedule table Initialization ************************/
static const lin_schedule_data_t LI0_NormalTable_data[16] = {

   {LI0_BDC_1_Cmd, 4, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
   , {LI0_BDC_1_Rsp, 4, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
   , {LI0_BDC_2_Cmd, 4, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
   , {LI0_BDC_2_Rsp, 4, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
   , {LI0_CCV4_Cmd, 4, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
   , {LI0_CCV4_Rsq, 4, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
   , {LI0_ATC_4, 4, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
   , {LI0_EXV_2, 4, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
   , {LI0_VCU_EXV, 4, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
   , {LI0_EXV_VCU, 4, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
   , {LI0_VCU_EXV2, 4, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
   , {LI0_EXV2_VCU, 4, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
   , {LI0_ECM_AGM_A_DEMAND, 4, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
   , {LI0_AGM_A_ECM_STATUS, 4, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
   , {LI0_ECM_AGM_B_DEMAND, 4, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
   , {LI0_AGM_B_ECM_STATUS, 4, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
};


/******************** Schedule table Initialization ************************/
/* If not specify by users, then by default delay of this schedule table is: */
/* (1.4*(34+10*(8+1))*1000/LIN_speed+jitter) ms, then rounded up to a value */
/* that is multiple of time base */
static const lin_schedule_data_t LI0_MasterReqTable_data[1] = {

   {LI0_MasterReq, 6, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
};
/******************** Schedule table Initialization ************************/
/* If not specify by users, then by default delay of this schedule table is: */
/* (1.4*(34+10*(8+1))*1000/LIN_speed+jitter) ms, then rounded up to a value */
/* that is multiple of time base */
static const lin_schedule_data_t LI0_SlaveRespTable_data[1] = {

   {LI0_SlaveResp, 6, {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}}
  
};

/********************* Schedule table structure Initialization ***************/
static const lin_schedule_t lin_schedule_tbl[LIN_NUM_OF_SCHD_TBL] ={

   /*interface_name = LI0 */
   {0, LIN_SCH_TBL_NULL  ,(lin_schedule_data_t*)0 }
  
   ,{1, LIN_SCH_TBL_GO_TO_SLEEP  , &LI0_lin_gotosleep_data[0] }
  
   ,{1, LIN_SCH_TBL_DIAG  , &LI0_MasterReqTable_data[0] }
  
   ,{1, LIN_SCH_TBL_DIAG  , &LI0_SlaveRespTable_data[0] }
  
   ,{16, LIN_SCH_TBL_NORM  , &LI0_NormalTable_data[0] }
  
};
/****************************LIN interface configuration ****************************/
const lin_protocol_user_config_t g_lin_protocol_user_cfg_array[LIN_NUM_OF_IFCS] = {

    /* Interface_name = LI0 */
    {
        .protocol_version = LIN_PROTOCOL_21,         /*lin_protocol_version */
        .language_version = LIN_PROTOCOL_21,         /*lin_language_version */
        .diagnostic_class = LIN_DIAGNOSTIC_CLASS_I,            /* LIN Diagnostic Class */
        .function = (bool)LIN_MASTER,                 /*  function LIN_MASTER*/

        .number_of_configurable_frames = 18,                            /*  num_of_frames */
        .frame_start = 0,                              /*  frame_start */
        .frame_tbl_ptr = lin_frame_tbl,                                          /*  frame_tbl */

        .list_identifiers_ROM_ptr = LI0_lin_configuration_ROM,       /*  *configuration_ROM */
        .list_identifiers_RAM_ptr = LI0_lin_configuration_RAM,       /*  *configuration_RAM */
        .max_idle_timeout_cnt =  10000,     /* Max Idle Timeout Count */
        .num_of_schedules = 5,                                  /*  num_of_schedules */
        .schedule_start = 0,                                  /*  schedule_start */
        .schedule_tbl = lin_schedule_tbl,             /* schedule_tbl */

        .slave_ifc_handle = INVALID_SLAVE_INDEX,
        .master_ifc_handle = LI0_Master,
        .lin_user_config_ptr = &lin1_InitConfig0,
#if (SUPPORT_TRANSPORT_LAYER == 1U)
        .tl_tx_queue_data_ptr = LI0_tl_tx_queue_data,
        .tl_rx_queue_data_ptr = LI0_tl_rx_queue_data,
        .max_message_length = 6             /* Max message length */
#endif /* end (SUPPORT_TRANSPORT_LAYER == 1U) */
    }
};

/*FUNCTION**********************************************************************
 *
 * Function Name : ld_read_by_id_callout
 * Description   : This function is an example of response; real implementation is application-dependent
 *                 You can use one of the following define to set PCI of response frame for
 *                 this service to the correct value
 * Implements    : ld_read_by_id_callout_Activity
 *END**************************************************************************/

l_u8 ld_read_by_id_callout(l_ifc_handle iii, l_u8 id, l_u8 *data)
{
    l_u8 retval = LD_NEGATIVE_RESPONSE;

    /* Get the current configuration */
    const lin_protocol_user_config_t  *prot_user_config_ptr = &g_lin_protocol_user_cfg_array[iii];

    if (prot_user_config_ptr->function == (bool)LIN_SLAVE)
    {
        /* Following code is an example - Real implementation is application-dependent */
        /* the handling does essentially depend on the id of the requested item */
        /* This example implement with ID = 32 - LIN_READ_USR_DEF_MIN */
        if (id == LIN_READ_USR_DEF_MIN)
        {
            /*
            * id received is user defined 32
            */
            /* A positive response is ready to be sent to the user defined request */
            data[0] = (l_u8) (id + 1U);    /* Data user define */
            data[1] = (l_u8) (id + 2U);    /* Data user define */
            data[2] = (l_u8) (id + 3U);    /* Data user define */
            data[3] = (l_u8) (id + 4U);    /* Data user define */
            data[4] = (l_u8) (id + 5U);    /* Data user define */
            retval = LD_POSITIVE_RESPONSE;
        }
        else
        {
            /*
            * id received is user defined 63 - no response
            */
        }
    } /* End (conf->function == _SLAVE_) */
   return retval;
}

